data: census_clean.csv
random_seed: 42
train_params:
  iterations: 100
  depth: 7
  loss_function: Logloss
categorical_features:
  - workclass
  - education
  - marital_status
  - occupation
  - relationship
  - race
  - sex
  - native_country
model_output: model.pkl
encoder_output: encoder.pkl
label_binarizer_output: lb.pkl